# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  app.pageRequest.action_listener:
    class:  AppBundle\EventListener\PageRequestListener
    arguments:
      - %paginator_param_page%
      - %paginator_param_sort%
      - %paginator_param_direction%
      - %paginator_param_page_size%
      - %paginator_default_page_size%
      - %paginator_default_distinct%
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
